### ISSUE TITLE
请问这个能作为服务器使用吗？

### ISSUE THREAD

**Issue by WKJay** [RT-Thread-packages/nopoll#6]
examples里面是客户端的示例，那请问是否可以作为服务器使用？

**Comment by hellozimo** [comment]
nopoll 本身提供了服务端的实现，请参考官方资料 http://www.aspl.es/nopoll/html/nopoll_core_library_manual.html#creating_basic_web_socket_server

**Comment by WKJay** [comment]
> nopoll 本身提供了服务端的实现，请参考官方资料 http://www.aspl.es/nopoll/html/nopoll_core_library_manual.html#creating_basic_web_socket_server

已找到，谢谢解答！
