### ISSUE TITLE
wss模式

### ISSUE THREAD

**Issue by GarMingLi** [RT-Thread-packages/nopoll#8]
这个可以在websocket的ws模式下使用，但是怎么在wss模式下实现websocket的client呢？

**Comment by hellozimo** [comment]
在 wss 模式下，使用的是 mbedtls 接口提供通讯加密

**Comment by joy-shuang** [comment]
我有修改好的基于mbedtls接口的
https://gitee.com/linux_shuang/nopoll_mbedtls_rtt.git

**Comment by joy-shuang** [comment]
> 这个可以在websocket的ws模式下使用，但是怎么在wss模式下实现websocket的client呢？
我有修改好的基于mbedtls接口的
参考使用：https://gitee.com/linux_shuang/nopoll_mbedtls_rtt.git
-----------------------------------------------
因为含有公司内容暂时不公开了，如果有需要可以联系我
