### ISSUE TITLE
使用dfs时的bug

### ISSUE THREAD

**Issue by joy-shuang** [RT-Thread-packages/nopoll#9]
启用dfs后使用lwip的两个问题：
1. nopoll soket接口都会结果dfs->net，nopoll在关闭时首先调用了shutdown函数，而shutdown后dfs中的fd会被清除，调用nopoll_socket_close时关闭的是dfs的fd不是lwip的sock
2.使用nopoll_loop_wait时使用的select监听的是dfs的fd不是lwip的sock
以上两个问题望采纳，

**Comment by hellozimo** [comment]
使用 master 分支的 RT-Thread。

maser 分支的 RT-Thread 已经解决了部分 shutdown 的问题，参考：

https://github.com/RT-Thread/rt-thread/pull/2382
https://github.com/RT-Thread/rt-thread/pull/1798

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/5731
